# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ls -lah
    cat index.html
  displayName: View index file and list folder
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'szymon-github'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.SourceVersion)'
    title: '$(Build.SourceVersion)'
    releaseNotesSource: 'inline'
    releaseNotesInline: '$(Build.SourceVersion)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'